CREATE TABLE `GoIT`.`CARS` (
  `MACKER` VARCHAR(45) NOT NULL,
  `SHOP` VARCHAR(45) NULL,
  `PHONE_NUMBER` VARCHAR(45) NULL,
  PRIMARY KEY (`MACKER`));

INSERT INTO `GoIT`.`CARS` (`MACKER`, `SHOP`, `PHONE_NUMBER`) VALUES ('BMW', 'ATLANT', '044-223-23-23');
INSERT INTO `GoIT`.`CARS` (`MACKER`, `SHOP`, `PHONE_NUMBER`) VALUES ('AUDI', 'ATILA', '044-187-95-23');
INSERT INTO `GoIT`.`CARS` (`MACKER`, `SHOP`, `PHONE_NUMBER`) VALUES ('NISSAN', 'FLASH', '044-555-89-62');

SELECT * FROM `GoIT`.`CARS`;

CREATE TABLE `GoIT`.`PHONE_NUMBERS` (
  `SHOP` VARCHAR(45) NOT NULL,
  `PHINE_NUMBER` VARCHAR(45) NULL,
  PRIMARY KEY (`SHOP`));

INSERT INTO `GoIT`.`PHONE_NUMBERS` (`SHOP`, `PHONE_NUMBER`) VALUES ('ATLANT', '044-223-23-23');
INSERT INTO `GoIT`.`PHONE_NUMBERS` (`SHOP`, `PHONE_NUMBER`) VALUES ('ATILA', '044-187-95-23');
INSERT INTO `GoIT`.`PHONE_NUMBERS` (`SHOP`, `PHONE_NUMBER`) VALUES ('FLASH', '044-555-89-62');


ALTER TABLE `GoIT`.`CARS`
DROP COLUMN `PHONE_NUMBER`;

COMMIT;