CREATE TABLE `GoIT`.`CARS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MACKER` VARCHAR(45) NOT NULL,
  `MODEL` VARCHAR(45) NOT NULL,
  `PRICE` VARCHAR(45) NOT NULL,
  `DISCOUNT` INT NOT NULL,
  PRIMARY KEY (`ID`));

INSERT INTO `GoIT`.`CARS` (`MACKER`, `MODEL`, `PRICE`, `DISCOUNT`) VALUES ('BMW', 'X5', '3000000.00', '5');
INSERT INTO `GoIT`.`CARS` (`MACKER`, `MODEL`, `PRICE`, `DISCOUNT`) VALUES ('BMW', 'X5m', '4000000.00', '5');
INSERT INTO `GoIT`.`CARS` (`MACKER`, `MODEL`, `PRICE`, `DISCOUNT`) VALUES ('BMW', 'M3', '1200000.00', '5');
INSERT INTO `GoIT`.`CARS` (`MACKER`, `MODEL`, `PRICE`, `DISCOUNT`) VALUES ('NISSAN', 'GT-R', '3200000.00', '10');

SELECT * FROM `GoIT`.`CARS`;

DROP TABLE `GoIT`.`CARS`;

CREATE TABLE `GoIT`.`CARS` (
  `MODEL` VARCHAR(45) NOT NULL,
  `MAKER` VARCHAR(45) NULL,
  `PRICE` VARCHAR(45) NULL,
  PRIMARY KEY (`MODEL`));

INSERT INTO `GoIT`.`CARS` (`MACKER`, `MODEL`, `PRICE`) VALUES ('BMW', 'X5', '3000000.00');
INSERT INTO `GoIT`.`CARS` (`MACKER`, `MODEL`, `PRICE`) VALUES ('BMW', 'X5m', '4000000.00');
INSERT INTO `GoIT`.`CARS` (`MACKER`, `MODEL`, `PRICE`) VALUES ('BMW', 'M3', '1200000.00');
INSERT INTO `GoIT`.`CARS` (`MACKER`, `MODEL`, `PRICE`) VALUES ('NISSAN', 'GT-R', '3200000.00');

CREATE TABLE `GoIT`.`DISCOUNT` (
  `MACKER` VARCHAR(45) NOT NULL,
  `DISCOUNT` INT NULL,
  PRIMARY KEY (`MACKER`));

INSERT INTO `GoIT`.`CARS` (`MACKER`, `DISCOUNT`) VALUES ('BMW', '5');
INSERT INTO `GoIT`.`CARS` (`MACKER`, `DISCOUNT`) VALUES ('NISSAN', '10');



COMMIT;


