--Find maker who develope one product type, but few models;
SELECT MACKER ,TYPE
FROM PRODUCT
WHERE MACKER IN (SELECT MACKER
                 FROM (
                      SELECT MACKER,TYPE
                      FROM PRODUCT
                      GROUP BY MACKER,TYPE) T1
GROUP BY MACKER
HAVING COUNT(*)=1 )
GROUP BY MACKER,TYPE
HAVING COUNT(*)>1

--Find the makers of the cheapest color printers;
SELECT DISTINCT PRODUCT.MACKER ,PRINTER.PRICE
FROM PRODUCT
INNER JOIN PRINTER
ON PRODUCT.MODEL=PRINTER.MODEL
WHERE PRINTER.PRICE IN (SELECT MIN(PRICE) FROM PRINTER WHERE COLOR='1') AND PRINTER.COLOR='1'

--Find the makers producing at least two distinct models of PCs;
SELECT MACKER, COUNT(MODEL)
FROM PRODUCT WHERE TYPE='PC'
GROUP BY MACKER
HAVING COUNT(MODEL)>=3
