USE `SQL`
SET @a = 'Lenova';
SELECT * FROM (
        SELECT * FROM `SQL`.PC
        INNER JOIN `SQL`.PRODUCT
        ON PRODUCT.MODEL=PC.MODEL WHERE PRODUCT.MAKER=@a) as t1;



--Find maker who create one product type, but few models;
USE `SQL`
SELECT MAKER ,TYPE
FROM `SQL`.PRODUCT
WHERE MAKER IN (SELECT MAKER
                 FROM (
                      SELECT MAKER,TYPE
                      FROM PRODUCT
                      GROUP BY MAKER,TYPE) T1
GROUP BY MAKER
HAVING COUNT(*)=1 )
GROUP BY MAKER,TYPE
HAVING COUNT(*)>1

--Find the makers of the cheapest color printers;
SELECT DISTINCT PRODUCT.MAKER ,`SQL`.PRINTER.PRICE
FROM `SQL`.PRODUCT
INNER JOIN `SQL`.PRINTER
ON PRODUCT.MODEL=`SQL`.PRINTER.MODEL
WHERE `SQL`.PRINTER.PRICE IN (SELECT MIN(PRICE) FROM `SQL`.PRINTER WHERE COLOR='1') AND `SQL`.PRINTER.COLOR='1'

--Find the makers producing at least two distinct models of PCs;
SELECT MACKER, COUNT(MODEL)
FROM PRODUCT WHERE TYPE='PC'
GROUP BY MACKER
HAVING COUNT(MODEL)>=3
