Use `GoIT`
BEGIN;
 SHOW CREATE TABLE GoIT.Students;
COMMIT;

USE `GoIT`
BEGIN;
CREATE TEMPORARY TABLE IF NOT EXISTS `GoIT`.`TEACHERS` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC));
COMMIT;


BEGIN;
TRUNCATE `GoIT`.`Students`;
COMMIT;

SELECT * FROM `GoIT`.`Students`;